services:
  database:
    image: postgres:17.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pharmacy
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0.11-alpine
    restart: always
    ports:
      - 6379:6379
